### ISSUE TITLE
I dont know what is happening, when i load the bot up, this happens.

### ISSUE THREAD

**Issue by Alideew1234** [ihaveamac/Kurisu#268]
Addon "Assistance" loaded
Addon "Blah" loaded
Addon "Err" loaded
Addon "Events" loaded
Addon "Extras" loaded
Loading fc.sqlite
Addon "FriendCode" loaded
addons.kickban failed to load.
ModuleNotFoundError: No module named 'pyaes'
Addon "Load" loaded
Addon "Lockdown" loaded
Addon "Logs" loaded
addons.loop failed to load.
ModuleNotFoundError: No module named 'feedparser'
Addon "Memes" loaded
Addon "Helper_list" loaded
Addon "ModStaff" loaded
Addon "ModWarn" loaded
Addon "Modwatch" loaded
Addon "Mod" loaded
Addon "NXErr" loaded
Addon "Rules" loaded
addons.xkcdparse failed to load.
ModuleNotFoundError: No module named 'xkcd'
Bot directory:  C:\Users\Alistair Deane-Wake\Desktop\Kurisu-master
NukeMusic has started! NukeFX OLD has 8 members!
Task exception was never retrieved
future: <Task finished coro=<Client._run_event() done, defined at C:\Users\Alistair Deane-Wake\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py:304> exception=IndexError('tuple index out of range',)>
Traceback (most recent call last):
  File "C:\Users\Alistair Deane-Wake\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "run.py", line 259, in on_ready
    await bot.send_message(bot.helpers_channel, msg)
  File "C:\Users\Alistair Deane-Wake\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 1144, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "C:\Users\Alistair Deane-Wake\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alistair Deane-Wake\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 312, in _run_event
    yield from self.on_error(event, *args, **kwargs)
  File "run.py", line 140, in on_error
    if isinstance(args[0], commands.errors.CommandNotFound):
IndexError: tuple index out of range

**Comment by Jisagi** [comment]
If you read what's in the README you would know that this is not a bot for general usage but rather a higly customized for a specific server.

> "Although it is open source, this bot is not really designed to be used in other setups at the moment; the source is mainly just available for those interested in how it works on the Nintendo Homebrew server."

**Comment by ihaveamac** [comment]
install the modules listed, and make sure you have replacements for all of the roles in run.py. or edit the source to replace the channels.
